app = "jobs-scraper"

[build]
dockerfile = "Dockerfile"

[processes]
scraper = "java -jar /app/app.jar"

# La máquina se prende sola cuando Fly.io la necesita
[machines.autostart]
processes = ["scraper"]

# La máquina se apaga cuando termina
[machines.autostop]
processes = ["scraper"]

# CRON JOB REAL

[[machine]]
cron = "0 */3 * * *"
process = "scraper"
